ray_config:
  num_cpus: 6
  num_gpus: 0
  ignore_reinit_error: true
  logging_level: info
  # logging_level: debug

env_config:
  debug: true

agent_config:
  agent: dqn.DQNTrainer
  framework: torch
  # NOTE: num_workers*num_cpus_per_worker should not exceed num_cpus 
  num_workers: 3
  num_cpus_per_worker: 2
  num_envs_per_worker: 2
  ignore_worker_failures: true
  disable_env_checking: true
  double_q: true
  dueling: true
  noisy: false
  replay_buffer_config:
    capacity: 1000000
  n_step: 16
  target_network_update_freq: 8000
  lr: 0.0000625
  adam_epsilon: .00015
  hiddens: [256, 256]
  rollout_fragment_length: 300
  train_batch_size: 32
  exploration_config:
    epsilon_timesteps: 200000
    final_epsilon: 0.01

other_config:
  num_train_iter: 1000
  # num_train_iter: 0
  save_dir: ray_outputs
  # saving and reporting frequency in terms of training iterations
  save_freq: 100
